baseurl = ""
googleAnalytics = ""
title = "Frank Schilbach"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Frank Schilbach"

[params]
title = "Associate Professor of Economics,"
institution = "Massachusetts Institute of Technology"
logo = "Frank_profile.jpg"
Twitter = "@frankschilbach"
Email = "fschilbach@mit.edu"
